import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import localFont from 'next/font/local';
import Footer from "@/components/Footer";
import ScrollLabel from "@/components/ScrollLabel";
import "remixicon/fonts/remixicon.css";

const Montserrat = localFont({
  src: 'font/Montserrat.woff2',
  variable: "--font-montserrat",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ratih Creative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} antialiased text-white -pt-20 transition-all`}
      >
      <Header />
        {children}
      <Footer />
      <ScrollLabel />
      </body>
    </html>
  );
}
