import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import "remixicon/fonts/remixicon.css";
import SiteLayout from "@/components/SiteLayout";

const Montserrat = localFont({
  src: 'font/Montserrat.woff2',
  variable: "--font-montserrat",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ratih Creative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Montserrat.variable} antialiased text-white transition-all`}
      >
        <SiteLayout>
          {children}
        </SiteLayout>
      </body>
    </html>
  );
}

